const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const file=require('node:path').join(__dirname,'../assets/card-practice.js');
const api=fs.existsSync(file)?require(file):{};
const input={event:' 昨晚收起屏幕时，我提高了声音。 ',note:' 我先喝水，后来放低声音重新开口。 '};
const options={id:'personal-1',now:'2026-09-09T10:00:00.000Z'};
test('exports four distinct practice types',()=>assert.deepEqual(api.types,['action','strength','mirror','repair']));
test('creates personal cards preserving supplied facts without mutating inputs',()=>{const before=JSON.stringify(input);for(const type of api.types){const c=api.prepare(type,input,options);assert.equal(c.type,type);assert.equal(c.id,options.id);assert.equal(c.createdAt,options.now);assert.equal(c.provenance,'personal');assert.deepEqual(c.source,{kind:'practice'});assert.ok(c.summary.some(s=>s.includes(input.event.trim())));assert.ok(c.summary.some(s=>s.includes(input.note.trim())));assert.ok(c.title);assert.equal(JSON.stringify(input),before);}});
test('rejects unknown types, missing fields, invalid ids and oversize input',()=>{assert.throws(()=>api.prepare('unknown',input,options));for(const data of [{},{event:'x',note:' '},{event:' ',note:'y'},{event:12,note:'y'},{event:'x'.repeat(1201),note:'y'}])assert.throws(()=>api.prepare('action',data,options));assert.throws(()=>api.prepare('action',input,{}));});
test('strength reflects a concrete action and repair leaves other person free',()=>{const strength=api.prepare('strength',input,options).summary.join(' ');assert.match(strength,/具体行为/);assert.doesNotMatch(strength,/你是.*家长|孩子是|能力很强/);const repair=api.prepare('repair',input,options).summary.join(' ');assert.match(repair,/承担/);assert.match(repair,/不需要.*谅解/);});
test('editor provides distinct prompts, labeled fields and deliberate exits',()=>{const outputs=api.types.map(t=>api.render(t,{}));assert.equal(new Set(outputs).size,4);for(const html of outputs){assert.match(html,/xp-page secondary-page/);assert.match(html,/data-xp-action="back"/);assert.match(html,/for="xpCardEvent"/);assert.match(html,/for="xpCardNote"/);assert.match(html,/仅保存在本机/);assert.match(html,/data-xp-action="card-prepare"/);assert.doesNotMatch(html,/undefined|null/);}});
test('card results stay hidden before an explicit flip and expose save after flip',()=>{const card=api.prepare('action',input,options);const back=api.render('action',{...input,card});assert.match(back,/data-xp-action="card-flip"/);assert.doesNotMatch(back,/data-xp-action="card-save"/);assert.doesNotMatch(back,/昨晚收起/);const front=api.render('action',{...input,card,flipped:true});assert.match(front,/昨晚收起/);assert.match(front,/data-xp-action="card-save"/);assert.match(front,/data-xp-action="card-edit"/);assert.match(front,/data-route="treasure-box"/);const saved=api.render('action',{card,flipped:true,saved:true});assert.match(saved,/已存入百宝箱/);assert.doesNotMatch(saved,/data-xp-action="card-save"/);});
test('escapes input, imported card content and handles invalid route',()=>{const hostile='<img src=x onerror=bad()>';const editor=api.render('mirror',{event:hostile,note:'</textarea><script>bad()</script>'});assert.doesNotMatch(editor,/<img|<script>/);assert.match(editor,/&lt;img/);const front=api.render('repair',{card:{title:hostile,summary:[hostile]},flipped:true});assert.doesNotMatch(front,/<img/);assert.match(front,/&lt;img/);assert.match(api.render('missing'),/暂时找不到/);});
test('can load as browser global and respects provided escaping callback',()=>{const context={};vm.runInNewContext(fs.readFileSync(file,'utf8'),context);assert.equal(typeof context.QZLCardPractice.render,'function');let count=0;api.render('action',{event:'hello'},s=>{count++;return String(s||'').replace(/</g,'&lt;');});assert.ok(count>0);});

test('saved cards offer a separate new-card action while edit keeps its own action',()=>{for(const type of api.types){const card=api.prepare(type,input,options);const saved=api.render(type,{card,flipped:true,saved:true});assert.match(saved,new RegExp('data-xp-action="card-new" data-type="'+type+'"'));assert.match(saved,/再记一张/);assert.match(saved,/data-xp-action="card-edit"/);assert.doesNotMatch(api.render(type,{card,flipped:true}),/data-xp-action="card-new"/);}});
